


iris.csv not found in tflearn examples
======================================================================================

 Error in py_call(attrib, args, keywords) :
  NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\jjallaire\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\data\iris.csv : The system cannot find the file specified.

Detailed traceback:
    C:\Users\jjallaire\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py (line105): load_iris
    C:\Users\jjallaire\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py (line54): load_csv_with_header
    C:\Users\jjallaire\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py (line162): __next__
    C:\Users\jjallaire\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py (line156): next
    C:\Users\jjallaire\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py (line123): readline


fully connected feed fails with "Unsupported feed type"
======================================================================================

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/tf_session_helper.cc

Error in py_call(attrib, args, keywords) :
  InternalError: Unsupported feed type
Detailed traceback:
    C:\Users\jjallaire\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py (line964): _run
    C:\Users\jjallaire\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py (line1014): _do_run
    C:\Users\jjallaire\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py (line1034): _do_call



test with anaconda for windows
======================================================================================




